=== TxN/WarpDrive/src/main/resources/config/WarpDrive.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	version="1.0"
	elementFormDefault="qualified"
	targetNamespace="WarpDrive"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="forElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="importElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="fillerElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="metashell" type="metashellElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="replacement" type="replacementElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="shell" type="shellElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="variable" type="xs:string" use="required" />
		<xs:attribute name="from" type="xs:string" use="optional" />
		<xs:attribute name="to" type="xs:string" use="optional" />
		<xs:attribute name="in" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="fillerSetElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="importElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="fillerElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="importElement">
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="fillerElement">
		<xs:attribute name="block" type="xs:string" use="required" />
		<xs:attribute name="metadata" type="xs:string" use="optional" />
		<xs:attribute name="nbt" type="xs:string" use="optional" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="structureElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="importElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="metashell" type="metashellElement" minOccurs="0" maxOccurs="1" />
			<xs:element name="shell" type="shellElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
    <xs:complexType name="schematicElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="replacement" type="replacementElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
        <xs:attribute name="group" type="xs:string" use="required" />
        <xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="filename" type="xs:string" use="required" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
        <xs:attribute name="mods" type="xs:string" use="optional" />
    </xs:complexType>
	
	<xs:complexType name="replacementElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="importElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="fillerElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="block" type="xs:string" use="required" />
		<xs:attribute name="metadata" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="lootSetElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="loot" type="lootElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="lootElement">
		<xs:attribute name="item" type="xs:string" use="required" />
		<xs:attribute name="damage" type="xs:string" use="optional" />
		<xs:attribute name="nbt" type="xs:string" use="optional" />
		<xs:attribute name="minQuantity" type="xs:string" use="optional" />
		<xs:attribute name="maxQuantity" type="xs:string" use="optional" />
		<xs:attribute name="weight" type="xs:string" use="optional" />
		<xs:attribute name="ratio" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="metashellElement">
		<xs:attribute name="block" type="xs:string" use="optional" />
		<xs:attribute name="metadata" type="xs:string" use="optional" />
		<xs:attribute name="minCount" type="xs:string" use="required" />
		<xs:attribute name="maxCount" type="xs:string" use="required" />
		<xs:attribute name="minRadius" type="xs:string" use="required" />
		<xs:attribute name="relativeRadius" type="xs:string" use="required" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="shellElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="import" type="importElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="filler" type="fillerElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="minThickness" type="xs:string" use="required" />
		<xs:attribute name="maxThickness" type="xs:string" use="required" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	
	<xs:complexType name="celestialObjectElement">
		<xs:sequence>
			<xs:element name="parent" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:annotation>
						<xs:documentation xml:lang="en">
							Coordinates in parent celestial object
							Optional: when not defined, current celestial object is an hyperspace dimension.
						</xs:documentation>
					</xs:annotation>
					<xs:sequence>
						<xs:element name="center" type="positionElement" minOccurs="1" maxOccurs="1" />
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
			
			<xs:element name="size" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="x" type="worldSizeType" use="required" />
					<xs:attribute name="z" type="worldSizeType" use="required" />
				</xs:complexType>
			</xs:element>
			
			<xs:element name="dimension" type="dimensionElement" minOccurs="0" maxOccurs="1" />
			
			<xs:element name="skybox" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:annotation>
						<xs:documentation xml:lang="en">
							Sky rendering parameters
						</xs:documentation>
					</xs:annotation>
					<xs:sequence>
						<xs:element name="backgroundColor" type="colorElement" minOccurs="0" maxOccurs="1" />
						<xs:element name="starBrightnessBase" type="xs:float" minOccurs="0" maxOccurs="1" />
						<xs:element name="starBrightnessVanilla" type="xs:float" minOccurs="0" maxOccurs="1" />
						<xs:element name="celestialObjectOpacity" type="xs:float" minOccurs="0" maxOccurs="1" />
						<xs:element name="fogColor" type="colorElement" minOccurs="0" maxOccurs="1" />
						<xs:element name="fogFactor" type="colorElement" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="render" type="renderElement" minOccurs="0" maxOccurs="unbounded" />
			
			<xs:choice minOccurs="0" maxOccurs="1">
				<xs:element name="for" type="forElement" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="celestialObject" type="celestialObjectElement" minOccurs="0" maxOccurs="unbounded" />
			</xs:choice>
		</xs:sequence>
		
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="dimensionElement">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Defines the actual game world characteristics.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="center" type="positionElement" minOccurs="1" maxOccurs="1" />
			<xs:element name="generate" type="generateElement" minOccurs="0" maxOccurs="unbounded" />
			<!-- <xs:element name="effects" type="effectElement" minOccurs="0" maxOccurs="unbounded" /> @TODO Not implemented -->
		</xs:sequence>
		
		<xs:attribute name="id" type="xs:int" use="required" />		
		<xs:attribute name="isProvidedByWarpDrive" type="xs:boolean" use="optional" default="false" />
		<xs:attribute name="isBreathable" type="xs:boolean" use="required" />
		<xs:attribute name="gravity" use="required">
			<xs:simpleType>
				<xs:union memberTypes="xs:double">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="none" />
							<xs:enumeration value="legacySpace" />
							<xs:enumeration value="legacyHyperspace" />
							<xs:enumeration value="normal" />
						</xs:restriction>
					</xs:simpleType>
				</xs:union>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="positionElement">
		<xs:attribute name="x" type="worldPositionType" use="required" />
		<xs:attribute name="z" type="worldPositionType" use="required" />
	</xs:complexType>
	
	<xs:complexType name="colorElement">
		<xs:attribute name="red" type="xs:float" use="required" />
		<xs:attribute name="green" type="xs:float" use="required" />
		<xs:attribute name="blue" type="xs:float" use="required" />
	</xs:complexType>
	
	<xs:complexType name="renderElement">
		<xs:attribute name="red" type="xs:float" use="required" />
		<xs:attribute name="green" type="xs:float" use="required" />
		<xs:attribute name="blue" type="xs:float" use="required" />
		<xs:attribute name="alpha" type="xs:float" use="required" />
		<xs:attribute name="texture" type="xs:string" use="optional" />
		<xs:attribute name="periodU" type="xs:double" use="optional" default="0.0" />
		<xs:attribute name="periodV" type="xs:double" use="optional" default="0.0" />
		<xs:attribute name="additive" type="xs:boolean" use="optional" default="false" />
	</xs:complexType>
	
	<xs:complexType name="generateElement">
		<xs:attribute name="group" type="xs:string" use="required" />
		<xs:attribute name="ratio" type="xs:string" use="required" />
	</xs:complexType>
	
	
	<xs:simpleType name="worldSizeType">
		<xs:restriction base="xs:unsignedInt">
			<xs:maxInclusive value="2000000" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="worldPositionType">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Vanilla block positions is limited to +/- 30000 km.
				Vanilla entities positions are computed on simple float precision, which is 6 digits precision => 1000 km.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="-1000000" />
			<xs:maxInclusive value="1000000" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="forRootElement">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="for" type="forRootElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="fillerSet" type="fillerSetElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="lootSet" type="lootSetElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="schematic" type="schematicElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="structure" type="structureElement" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="celestialObject" type="celestialObjectElement" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="variable" type="xs:string" use="required" />
		<xs:attribute name="from" type="xs:string" use="optional" />
		<xs:attribute name="to" type="xs:string" use="optional" />
		<xs:attribute name="in" type="xs:string" use="optional" />
		<xs:attribute name="mods" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:element name="worldGeneration">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="for" type="forRootElement" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="fillerSet" type="fillerSetElement" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="lootSet" type="lootSetElement" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="schematic" type="schematicElement" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="structure" type="structureElement" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="celestialObject" type="celestialObjectElement" minOccurs="0" maxOccurs="unbounded" />
			</xs:choice>
			<xs:attribute name="version" type="xs:string" use="required" fixed="2" />
			<xs:attribute name="mods" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== TxN/WarpDrive/src/main/resources/config/celestialObjects-default.xml
<?xml version="1.0" encoding="utf-8"?>
<worldGeneration version="2"
				 xmlns="WarpDrive"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="WarpDrive WarpDrive.xsd">
	
	<!--
	  An astronomical object or celestial object is a naturally occurring physical entity, association, or structure in the observable universe.
	  They can be a planet, a more abstract construct like solar system (space dimension) or the all mighty hyperspace.
	  Hyperspace is a dimension which is its own parent. In other words, hyperspace.dimensionId = hyperspace.parentDimensionId.
	  Space is a dimension with Hyperspace as its parent.
	  In theory, multiple planets can exists in the same minecraft world.
	  In theory, multiple hyperspaces can be defined.
	  -->
	
	
	<!-- Top level is hyperspace, typically a galaxy. -->
	<celestialObject group="milkyWay" name="hyperspace">
		<!--
		  side defines the world border size, measured in blocks. This is also the size of the orbit area in space, so don't go too big.
		  -->
		<size x="100000" z="100000" />
		
		<!--
		  dimension defines an actual game world. If it's missing, that celestialObject remains visible but you can't "land" on it.  
		  dimension.id: this is the id of the dimension. 0 is the Overworld, -1 is the Nether, 1 is the End.
		  dimension.isBreathable: this is a boolean flag defining if ambient atmosphere is breathable.
		  dimension.gravity: this is the gravity simulation type. 0 is vanilla, 1 is space, 2 is hyperspace.
		  dimension.center.x, dimension.center.z: those are the center coordinate of that dimension world border, measured in blocks. For convenience, it's usually 0, 0.
		  dimension.isProvidedByWarpDrive (optional): this is a boolean flag defining if WarpDrive provides this dimension or not.
		  Currently only Space and Hyperspace can be provided: use other mods to generate planet world.
		  -->
		<dimension id="-3" isBreathable="false" gravity="legacyHyperspace" isProvidedByWarpDrive="true">
			<center x="0" z="0" />
		</dimension>
		
		<!--
		  skybox defines the sky rendering while inside a WarpDrive provided dimensions.
		  Those can be adjusted to your lore: in hyperspace, Babylon 5 is redish, Stargate is bluish, etc.
		  skybox.backgroundColor is self explanatory. Vanilla enforces plain black at max render distance.
		  skybox.starBrightnessBase is the minimum brightness of stars in the sky.
		  skybox.starBrightnessVanilla is how much of the vanilla star brightness is used. Space and hyperspace have no Sun, hence it's a fixed value.
		  skybox.celestialObjectOpacity is used for that eery feeling. 0 will completly hide celestial objects.
		  skybox.fogColor is the main color. Higher values increases the halo effect.
		  skybox.fogFactor is the fog opacity depending on local Sun position. Space and hyperspace have no Sun, hence it's a fixed value.
		  -->
		<skybox>
			<backgroundColor red="1.0" green="0.0" blue="0.0" />
			<starBrightnessBase>0.2</starBrightnessBase>
			<starBrightnessVanilla>0.0</starBrightnessVanilla>
			<celestialObjectOpacity>0.3</celestialObjectOpacity>
			<fogColor red="0.15" green="0.0" blue="0.0" />
			<fogFactor red="0.0" green="0.0" blue="0.0" />
		</skybox>
		
		<!-- Second level is space, typically a star system. -->
		<celestialObject group="milkyWay" name="solarSystem">
			<!--
			  parent defines the relation with a bigger enveloping celestial object.
			  parent.group, parent.name (optional): when using multiple files, you can attach to a parent by its group and name.
			  parent.center.x, parent.center.z: this is the center coordinates in the parent dimension, measured in blocks.
			  -->
			<parent>
				<center x="0" z="0" />
			</parent>
			<size x="200000" z="200000" />
			<dimension id="-2" isBreathable="false" gravity="legacySpace" isProvidedByWarpDrive="true">
				<center x="0" z="0" />
				<!--
					generate defines the chance of different structures to generate
					generate.group, generate.name: identify the structure from the related XML files
					Those only works in WarpDrive dimensions, they're ignored otherwise.
				  -->
				<generate group="moon" ratio="0.008" />
				<generate group="asteroid" ratio="0.0015" />
				<generate group="asteroidField" ratio="0.006" />
			</dimension>
			
			<skybox>
				<backgroundColor red="0.0" green="0.0" blue="0.0" />
				<starBrightnessBase>0.9</starBrightnessBase>
				<starBrightnessVanilla>0.0</starBrightnessVanilla>
				<celestialObjectOpacity>1.0</celestialObjectOpacity>
				<fogColor red="0.0" green="0.0" blue="0.0" />
				<fogFactor red="0.0" green="0.0" blue="0.0" />
			</skybox>
			
			<!-- Sun is just displayed, there's no actual game dimension -->
			<celestialObject group="solarSystem" name="sun">
				<parent>
					<!-- sun is at the center of the solarSystem -->
					<center x="0" z="0" />
				</parent>
				<size x="10000" z="10000" />
				<!--
				  render defines several layers from surface to high atmosphere representing the planet.
				  red, green, blue: color mixing from 0.00 (black) to 1.00 (white)
				  alpha: transparency factor from 0.00 (invisible) to 1.00 (opaque)
				  texture: optional texture to use, can come from resource pack, vanilla or the mod itself
				  periodU, periodV: optional rotation period, measured in seconds, defaults to 0 (disabled)
				  additive: optional blending function, defaults to false (multiplicative)
				  -->
				<render red="0.80" green="0.50" blue="0.20" alpha="1.00" texture="" />
				<render red="0.80" green="0.70" blue="0.30" alpha="0.40" texture="warpdrive:textures/celestial/planet_icy.png" periodU="-20" periodV="104" additive="true" />
				<render red="0.80" green="0.55" blue="0.10" alpha="0.48" texture="warpdrive:textures/celestial/planet_metallic.png" periodU="-40" periodV="140" additive="true" />
				<render red="0.80" green="0.45" blue="0.30" alpha="0.34" texture="warpdrive:textures/celestial/planet_magma.png" periodU="24" periodV="-35" additive="true" />
				<render red="0.80" green="0.50" blue="0.20" alpha="0.08" texture="" />
				<render red="0.75" green="0.48" blue="0.20" alpha="0.08" texture="" />
				<render red="0.70" green="0.55" blue="0.20" alpha="0.08" texture="" />
			</celestialObject>
			
			<!-- Earth is the overworld (dimension.id is 0) -->
			<celestialObject group="solarSystem" name="earth">
				<parent>
					<!-- coordinates in the solar system, measured in blocks -->
					<center x="-40000" z="20000" />
				</parent>
				<size x="4000" z="4000" />
				<dimension id="0" isBreathable="true" gravity="normal">
					<center x="0" z="0" />
				</dimension>
				<render red="0.70" green="0.70" blue="0.70" alpha="1.00" texture="warpdrive:textures/celestial/planet_temperate.png" />
				<render red="0.90" green="0.95" blue="1.00" alpha="0.15" texture="warpdrive:textures/celestial/cloud_small.png" periodU="100" periodV="1100" additive="true" />
				<render red="0.90" green="0.90" blue="1.00" alpha="0.15" texture="warpdrive:textures/celestial/cloud_medium.png" periodU="300" periodV="1500" additive="false" />
				<render red="0.80" green="0.70" blue="1.00" alpha="0.15" texture="warpdrive:textures/celestial/cloud_large.png" periodU="500" periodV="2100" additive="false" />
				<render red="0.50" green="0.50" blue="1.00" alpha="0.08" />
				<render red="0.50" green="0.50" blue="1.00" alpha="0.08" />
				<render red="0.50" green="0.50" blue="1.00" alpha="0.08" />
				
				<!-- Hell is the nether. It's located below earth. In other words, falling below bedrock will drop you to the nether... -->
				<celestialObject group="solarSystem" name="hell">
					<parent>
						<center x="0" z="0" />
					</parent>
					<size x="1000" z="1000" />
					<dimension id="-1" isBreathable="true" gravity="normal">
						<center x="0" z="0" />
					</dimension>
				</celestialObject>
			</celestialObject>
			
			<!-- Pluto is The End. It's a far planet. --> 
			<celestialObject group="solarSystem" name="pluto">
				<parent>
					<center x="90000" z="70000" />
				</parent>
				<size x="4000" z="4000" />
				<dimension id="1" isBreathable="true" gravity="normal">
					<center x="0" z="0" />
				</dimension>
				<render red="1.00" green="1.00" blue="1.00" alpha="1.00" texture="minecraft:textures/blocks/end_stone.png" periodU="150" />
				<render red="0.50" green="0.50" blue="0.40" alpha="0.30" />
			</celestialObject>
			
		</celestialObject>
		
	</celestialObject>
	
</worldGeneration>

=== TxN/WarpDrive/src/main/resources/config/structures-ship.xml
<?xml version="1.0" encoding="utf-8"?>
<worldGeneration version="2"
				 xmlns="http://warpdrive.lemadec.org"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://warpdrive.lemadec.org WarpDrive.xsd">
	
	<schematic group="ship" name="legacy" filename="legacy" weight="1">
		<replacement block="minecraft:stone" metadata="0">
			<import group="hull_plain" name="%hull1%" />
		</replacement>
		<replacement block="minecraft:glass" metadata="0">
			<import group="hull_glass" name="%hull1%" />
		</replacement>
		<replacement block="minecraft:sandstone" metadata="0">
			<import group="hull_plain" name="%hull2%" />
		</replacement>
		<replacement block="minecraft:stained_glass" metadata="0">
			<import group="hull_glass" name="%hull2%" />
		</replacement>
		<replacement block="minecraft:wool" metadata="0">
			<for variable="colorMetadata" in="0,1,2,3,4,5,6,8">
				<filler block="minecraft:wool" metadata="%colorMetadata%" weight="1" />
			</for>
		</replacement>
		<replacement block="minecraft:wool" metadata="14">
			<for variable="colorMetadata" in="7,9,10,11,12,13,14,15,16">
				<filler block="minecraft:wool" metadata="%colorMetadata%" weight="1" />
			</for>
		</replacement>
		<replacement block="ComputerCraft:CC-Computer">
			<filler block="ComputerCraft:CC-Computer" weight="1" mods="ComputerCraft" />
			<filler block="minecraft:air" ratio="0.5" />
		</replacement>
	</schematic>
	
	<schematic group="ship" name="legacy" filename="legacy_corrupted" weight="1">
		<replacement block="minecraft:stone" metadata="0">
			<import group="hull_plain" name="%hull1%" />
			<filler block="minecraft:air" ratio="0.1" />
			<filler block="WarpDrive:blockShipCorruption" ratio="0.0025" />
		</replacement>
		<replacement block="minecraft:glass" metadata="0">
			<import group="hull_glass" name="%hull1%" />
			<filler block="minecraft:air" ratio="0.2" />
		</replacement>
		<replacement block="minecraft:sandstone" metadata="0">
			<import group="hull_plain" name="%hull2%" />
			<filler block="minecraft:air" ratio="0.1" />
			<filler block="WarpDrive:blockShipCorruption" ratio="0.0025" />
		</replacement>
		<replacement block="minecraft:stained_glass" metadata="0">
			<import group="hull_glass" name="%hull2%" />
			<filler block="minecraft:air" ratio="0.2" />
		</replacement>
		<replacement block="minecraft:stone" metadata="0">
			<import group="cable" />
			<filler block="minecraft:air" ratio="0.25" />
		</replacement>
		<replacement block="minecraft:glass" metadata="0">
			<import group="solar" />
			<filler block="minecraft:air" ratio="0.25" />
		</replacement>
		<replacement block="minecraft:wool" metadata="0">
			<for variable="colorMetadata" in="0,1,2,3,4,5,6,8">
				<filler block="minecraft:wool" metadata="%colorMetadata%" weight="1" />
			</for>
		</replacement>
		<replacement block="minecraft:wool" metadata="14">
			<for variable="colorMetadata" in="7,9,10,11,12,13,14,15,16">
				<filler block="minecraft:wool" metadata="%colorMetadata%" weight="1" />
			</for>
		</replacement>
		<replacement block="warpdrive:blockShipCore">
			<filler block="warpdrive:blockShipCore" weight="1" />
			<filler block="minecraft:air" ratio="0.5" />
		</replacement>
		<replacement block="warpdrive:blockAirGenerator">
			<filler block="warpdrive:blockAirGenerator" weight="1" />
			<filler block="minecraft:air" ratio="0.5" />
		</replacement>
		<replacement block="warpdrive:blockShipController">
			<filler block="warpdrive:blockShipController" weight="1" />
			<filler block="minecraft:air" ratio="0.5" />
		</replacement>
		<replacement block="ComputerCraft:CC-Computer">
			<filler block="ComputerCraft:CC-Computer" weight="1" mods="ComputerCraft" />
			<filler block="minecraft:air" ratio="0.5" />
		</replacement>
	</schematic>
	
	<structure group="ship" name="legacy" ratio="0.2">
	</structure>
	
</worldGeneration>
